apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saveursdegenie
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-cedille-production-v2
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2
    namespace: saveursdegenie
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production-v2
    path: apps/saveursdegenie/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true
